### PR TITLE
Add initial setup ready for when we test HomepagePopularLinksTest

### PR DESCRIPTION
**Pull request by georgeschena**
Trello: https://trello.com/c/GmoMiJii/2289-turn-on-popular-links-ab-test-100-z
Related work: https://github.com/alphagov/frontend/pull/3865

### CODE REVIEW

**Comment by hannako** [comment]
@georgeschena Thanks for picking this up George! I've set this to draft and DNM for now just to be safe :-)

I'll find out what percentages we need for each variant (A B and C) and let you know

**Comment by hannako** [comment]
Please could you update the percentages to be 0 A / 0 B / 0 C / 0 D / 100 Z and please can you rebase to get rid of the add empty line commits :-)

**Review by hannako — APPROVED** [review]
LGTM

**Review by leenagupte — APPROVED** [review]
Looks good. 👍

**Pull request merged**
